### PR TITLE
removed paco submodile, using coq-paco OPAM package instead 

### PR DESCRIPTION
**Pull request by vzaliva**
https://github.com/vellvm/vellvm/issues/64

### CODE REVIEW

**Comment by vzaliva** [comment]
I've tested with coq-8.8.1 and 8.8.2 using opam1 and opam2 respectively. `coq-paco` package seems to contain the most recent version and compatible with both.

As to opam2, in general, I am also struggling with the decision. I feel that moving to opam2 is the right step, but the main thing stopping me is the fact that there is no official package for Ubuntu. I already switched to opam2 on my mac machine which is using homebrew and it works without the problem so far and installs newer versions of several packages like dune, coq. On my main development machine, which is Ubuntu I am still on opam1 but planning to switch soon, using this https://discuss.ocaml.org/t/opam-2-0-experimental-ppas/2446

**Comment by vzaliva** [comment]
the reason Travis test fails on this pull request is because it is trying to build `lib/paco`. This step should be removed from the build process.

**Comment by vzaliva** [comment]
OK, I found and fixed travis config. CI tests pass now

**Comment by Zdancewic** [comment]
Thanks!  This looks great.

**Pull request merged**
