### PR TITLE
Removing dependency from CompCert

### PR DESCRIPTION
**Pull request by vzaliva**
Per https://github.com/vellvm/vellvm/issues/67 removed the dependency from CompCert.
Some library files copied over and ported to Flocq-3.0.0 (as in `coq-flocq` package).

### CODE REVIEW

**Comment by Zdancewic** [comment]
This patch looks good, but for some reason I'm running into issues installing coq-flocq via opam 2.0.  I think that the problem is with the sandboxing that opam 2.0 does and mac OSX 10.14, but I haven't tracked down the issue yet.  Did you have any issues with installing flocq?

**Comment by vzaliva** [comment]
I have coq-flocq installed under opam 1.2 (linux) and opam 2 (macOS + homebrew).

```
$ opam info coq-flocq

<><> coq-flocq: information on all versions <><><><><><><><><><><><><><><><>  🐫 
name                   coq-flocq
all-installed-versions 3.0.0 [default coq-8.7 4.07.1]
all-versions           2.2.0  2.3.0  2.4.0  2.5.2  2.6.1  3.0.0

<><> Version-specific details <><><><><><><><><><><><><><><><><><><><><><><>  🐫 
version       3.0.0
repository    coq-released
url.src:      "https://gforge.inria.fr/frs/download.php/file/37477/flocq-3.0.0.tar.gz"
url.checksum: "md5=11b80ed7e8395f8223e9f5d55a491bfe"
homepage:     "http://flocq.gforge.inria.fr/"
bug-reports:  "https://gitlab.inria.fr/flocq/flocq/issues"
dev-repo:     "https://gitlab.inria.fr/flocq/flocq"
authors:      "Sylvie Boldo <sylvie.boldo@inria.fr>"
              "Guillaume Melquiond <guillaume.melquiond@inria.fr>"
maintainer:   "guillaume.melquiond@inria.fr"
license:      "LGPL 3"
tags:         "keyword:floating point arithmetic"
flags:        light-uninstall
depends:      "ocaml" "coq" {>= "8.7" & < "8.9~"}
synopsis      A floating-point formalization for the Coq system.
```

I am unable to check for update now. It looks like `coq-released` opam repository is down:

```
$ opam info coq-flocq

<><> coq-flocq: information on all versions <><><><><><><><><><><><><><><><>  🐫 
name                   coq-flocq
all-installed-versions 3.0.0 [default coq-8.7 4.07.1]
all-versions           2.2.0  2.3.0  2.4.0  2.5.2  2.6.1  3.0.0

<><> Version-specific details <><><><><><><><><><><><><><><><><><><><><><><>  🐫 
version       3.0.0
repository    coq-released
url.src:      "https://gforge.inria.fr/frs/download.php/file/37477/flocq-3.0.0.tar.gz"
url.checksum: "md5=11b80ed7e8395f8223e9f5d55a491bfe"
homepage:     "http://flocq.gforge.inria.fr/"
bug-reports:  "https://gitlab.inria.fr/flocq/flocq/issues"
dev-repo:     "https://gitlab.inria.fr/flocq/flocq"
authors:      "Sylvie Boldo <sylvie.boldo@inria.fr>"
              "Guillaume Melquiond <guillaume.melquiond@inria.fr>"
maintainer:   "guillaume.melquiond@inria.fr"
license:      "LGPL 3"
tags:         "keyword:floating point arithmetic"
flags:        light-uninstall
depends:      "ocaml" "coq" {>= "8.7" & < "8.9~"}
synopsis      A floating-point formalization for the Coq system.
```

**Comment by Zdancewic** [comment]
I'm trying to install it using opam 2.0.0 on OSX (10.14 Mojave) with ocaml 4.06, coq 8.8.2.  I get what looks like a  permissions failure in the sandboxing:

```
opam install -v coq-flocq
The following actions will be performed:
  ∗ install coq-flocq 3.0.0

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
[coq-flocq.3.0.0] found in cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
+ /Users/stevez/.opam/opam-init/hooks/sandbox.sh "build" "./configure" "--libdir" "/Users/stevez/.opam/4.06.0/lib/coq/user-contrib/Flocq" (CWD=/Users/stevez/.opam/4.06.0/.opam-switch/build/coq-flocq.3.0.0)
- checking for g++... g++
- checking whether the C++ compiler works... yes
- checking for C++ compiler default output file name... a.out
- checking for suffix of executables... 
- checking whether we are cross compiling... no
- checking for suffix of object files... o
- checking whether we are using the GNU C++ compiler... yes
- checking whether g++ accepts -g... yes
- checking for coqc... /Users/stevez/.opam/4.06.0/bin/coqc
- checking for coqdep... /Users/stevez/.opam/4.06.0/bin/coqdep
- checking for coqdoc... /Users/stevez/.opam/4.06.0/bin/coqdoc
- configure: building remake...
- remake.cpp:2593:16: warning: 'tempnam' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of tempnam(3), it is highly recommended that you use mkstemp(3) instead. [-Wdeprecated-declarations]
-         socket_name = tempnam(NULL, "rmk-");
-                       ^
- /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/stdio.h:306:1: note: 'tempnam' has been explicitly marked deprecated here
- __deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of tempnam(3), it is highly recommended that you use mkstemp(3) instead.")
- ^
- /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/cdefs.h:180:48: note: expanded from macro '__deprecated_msg'
-         #define __deprecated_msg(_msg) __attribute__((deprecated(_msg)))
-                                                       ^
- 1 warning generated.
- configure: creating ./config.status
- config.status: creating Remakefile
- config.status: creating src/Version.v
+ /Users/stevez/.opam/opam-init/hooks/sandbox.sh "build" "./remake" "-j7" (CWD=/Users/stevez/.opam/4.06.0/.opam-switch/build/coq-flocq.3.0.0)
- Failed to create server: Operation not permitted
[ERROR] The compilation of coq-flocq failed at "/Users/stevez/.opam/opam-init/hooks/sandbox.sh build ./remake -j7".

#=== ERROR while compiling coq-flocq.3.0.0 ====================================#
# context     2.0.0 | macos/x86_64 | base-bigarray.base base-threads.base base-unix.base ocaml-base-compiler.4.06.0 | https://coq.inria.fr/opam/released
# path        ~/.opam/4.06.0/.opam-switch/build/coq-flocq.3.0.0
# command     ~/.opam/opam-init/hooks/sandbox.sh build ./remake -j7
# exit-code   1
# env-file    ~/.opam/log/coq-flocq-16632-05296d.env
# output-file ~/.opam/log/coq-flocq-16632-05296d.out
### output ###
# Failed to create server: Operation not permitted



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
┌─ The following actions failed
│ λ build coq-flocq 3.0.0
└─ 
```

**Comment by vzaliva** [comment]
@Zdancewic I just realized that I've already reported this issue and it is being fixed now: https://github.com/fblanqui/color/issues/12 

The workaround is to disable sandboxing by passing `--disable-sandboxing` to `opam init`

**Comment by Zdancewic** [comment]
I tried that, but it doesn't appear to change anything.  :-/

--Steve

**Comment by Zdancewic** [comment]
Ah -- it looks like I also need the --reinit flag.  It looks like this 
will now rebuild everything.  I'll see how it works.

--Steve

**Comment by Zdancewic** [comment]
The workaround for installing coq-flocq turned out to be temporarily removing the sandbox wrapping lines from ~/.opam/config. I'll make a note of this in the installation instructions.

**Pull request merged**
