### PR TITLE
Generate documentation using coq2html?

### PR DESCRIPTION
**Pull request by bollu**
Here's a PR in case `vellvm` wishes to use  `coq2html` to generate documentation. I personally like the output better than `coqdoc`.

EDIT: [Link to sample `Classes.v` documentation](https://bollu.github.io/vellvm/src/doc/html/Classes.html)

### CODE REVIEW

**Comment by Zdancewic** [comment]
This is a good idea.  Do you know if there's a way to generate the new Sphinx-ified documentation in the style of the reference manual?

**Comment by Zdancewic** [comment]
It looks like we need to add coq2html.css and coq2html.js to the doc directory.  Perhaps we should add coq2html as a git submodule in /lib (just like Paco) and fix the makefiles to assume that?

**Comment by bollu** [comment]
Yes, that makes sense. Sorry for not testing this properly, I must had this locally, but I didn't commit the right files...

**Comment by bollu** [comment]
[Here is the docs](https://github.com/coq/coq/tree/master/doc/sphinx#documenting-coq-with-sphinx) on how Coq generates sphinx docs.

**Pull request merged**
